package ru.cobalt42.ktMain.util.enums

enum class TargetUname(val uname: String){
    JOINT_CONCLUSION("jointConclusion"),
    TUBE_LINE("tubeLine"),
    CONSTRUCTION("construction"),
    DRAWING("drawing"),
    PERSON("person"),
    ORGANIZATION("organization"),
    HIDDEN_WORK_ACT("hiddenWorkAct"),
    PROJECT("project"),
    POSITION("position"),
    WORK("work"),
    INCOMING_CONTROL("incomingControl"),
    QUALITY_DOCUMENT("qualityDocument"),
    CORROSION_WORKS_JOURNAL("corrosionWorksJournal"),
    PROTECTIVE_COATING_ACT("protectiveCoatingAct"),
    DRAWING_REVISION("drawingRevision"),
    STRETCHING_COMPENSATOR_ACT("stretchingCompensatorAct"),
    JOINT_TUBE_LINE_PART("jointTubeLinePart"),
    EXECUTIVE_SCHEME("executiveScheme"),
    WORK_CONCLUSION("workConclusion"),
    TECHNOLOGICAL_CARD("technologicalCard"),
    DEFECTOSCOPIST_CERTIFICATE("defectoscopistCertificate"),
    MEASURING_INSTRUMENT("measuringInstrument"),
    TUBE_LINE_PART("tubeLinePart"),
    COATING_MATERIAL("coatingMaterial"),
    RESPONSIBLE_STRUCTURE_ACT("responsibleStructureAct"),
    DEBIT_COMMODITIES("debitCommodities"),
    UNIT("unit"),
    FASTENER_PART("fastenerPart"),
    WELDING_CONSUMABLE("weldingConsumable"),
    NAKS("naks"),
    BASIC_TEST_ACT("basicTestAct"),
    MECHANISM_TEST_ACT("mechanismTestAct"),
    TECHNOLOGICAL_NODE("technologicalNode"),
    EQUIPMENT("equipment"),
    FITTER_CERTIFICATE("fitterCertificate"),
    VESSEL_APPARATUS_TEST_ACT("vesselApparatusTestAct"),
    EQUIPMENT_DEFECT_ACT("equipmentDefectAct"),
    PASSING_EQUIPMENT_TO_INSTALLATION_ACT("passingEquipmentToInstallationAct"),
    EQUIPMENT_AFTER_INDIVIDUAL_TEST_ACT("equipmentAfterIndividualTestAct"),
    EQUIPMENT_AFTER_COMPLEX_TEST_ACT("equipmentAfterComplexTestAct"),
    EQUIPMENT_INSTALLATION_ON_FOUNDATION_ACT("equipmentInstallationOnFoundationAct"),
    WELDER_SKILL("welderSkill"),
    WELDER_ADMISSION_SHEET("welderAdmissionSheet"),
    SPECIFICATION("specification"),
    SPECIFICATION_REVISION("specificationRevision"),
}


