package ru.cobalt42.ktMain.model.common.project

data class TechNecessaryDocuments(
    var tubeLineRegistry: DocumentParameters = DocumentParameters(),
    var electrodeApproval: DocumentParameters = DocumentParameters(),
    var stretchingCompensatorAct: DocumentParameters = DocumentParameters(),
    var incomingControl: DocumentParameters = DocumentParameters(),
    var hiddenWorkAct: DocumentParameters = DocumentParameters(),
    var jointConclusionVik: DocumentParameters = DocumentParameters(),
    var jointConclusionRk: DocumentParameters = DocumentParameters(),
    var jointConclusion: DocumentParameters = DocumentParameters(),
    var jointConclusionPvkMpd: DocumentParameters = DocumentParameters(),
//    var jointMechanicalTestReport: DefaultDocument = DefaultDocument(),
    var tubeLineIsolationPermit: DocumentParameters = DocumentParameters(),
    var protectiveCoatingAct: DocumentParameters = DocumentParameters(),
    var basicTestPermit: DocumentParameters = DocumentParameters(),
    var basicTestAct: DocumentParameters = DocumentParameters(),
    var installedEquipmentAct: DocumentParameters = DocumentParameters(),
    var installedArmatureAndEquipmentStatement: DocumentParameters = DocumentParameters(),
    var responsibleStructureAct: DocumentParameters = DocumentParameters(),
    var intermediateResponsibleStructureAct: DocumentParameters = DocumentParameters(),
    var passingEquipmentToInstallationAct: DocumentParameters = DocumentParameters(),
    var equipmentDefectsAct: DocumentParameters = DocumentParameters(),
    var equipmentInstallationOnFoundationAct: DocumentParameters = DocumentParameters(),
    var vesselApparatusTestAct: DocumentParameters = DocumentParameters(),
    var mechanismTestAct: DocumentParameters = DocumentParameters(),
//    var engineeringSupportNet: DefaultDocument = DefaultDocument(),
    var flushingAct: DocumentParameters = DocumentParameters(),
    var blowdownAct: DocumentParameters = DocumentParameters(),
    var tubeCavityCleaningAct: DocumentParameters = DocumentParameters(),
    var equipmentAfterIndividualTestAct: DocumentParameters = DocumentParameters(),
    var equipmentAfterComplexTestAct: DocumentParameters = DocumentParameters(),
    var installationCertificate: DocumentParameters = DocumentParameters(),
    var tubeLineSpecification: DocumentParameters = DocumentParameters(),
//    var tubeLinePassport: DefaultDocument = DefaultDocument(),
//    var executiveGeodeticSurveyElevations: DefaultDocument = DefaultDocument(),
    var weldingJournal: DocumentParameters = DocumentParameters(),
//    var pilotJointLog: DefaultDocument = DefaultDocument(),
//    var jointHeatTreatmentJournal: DefaultDocument = DefaultDocument(),
//    var weldingConsumableQualityLog: DefaultDocument = DefaultDocument(),
//    var radiographicControlJournal: DefaultDocument = DefaultDocument(),
//    var ultrasonicInspectionJournal: DefaultDocument = DefaultDocument(),
//    var colorFlawDetectionJournal: DefaultDocument = DefaultDocument(),
//    var buildingStructureInstallJournal: DefaultDocument = DefaultDocument(),
    var jointCorrosionProtectionJournal: DocumentParameters = DocumentParameters(),
    var corrosionWorksJournal: DocumentParameters = DocumentParameters(),
//    var incomingControlJournal: DefaultDocument = DefaultDocument(),
    var connectionAssemblyJournal: DocumentParameters = DocumentParameters(),
    var weldingJournalMembersOne: DocumentParameters = DocumentParameters(),
    var weldingJournalMembersTwo: DocumentParameters = DocumentParameters(),
    var weldingJournalMembersThree: DocumentParameters = DocumentParameters(),
    var detachableConnectionFitterList: DocumentParameters = DocumentParameters(),
//    var welderMechanicalTestsConclusion: DefaultDocument = DefaultDocument(),
//    var complexAssemblyTubeLinePassport: DefaultDocument = DefaultDocument(),
)

